controller_list:
  - name: fake_arm_controller
    joints:
      - base_plate_to_base
      - base_to_shoulder
      - shoulder_to_main_arm
      - main_arm_to_elbow
      - elbow_to_forearm
      - forearm_to_wrist
      - wrist_to_hand
  - name: fake_probe_controller
    joints:
      []